name: DisplayEntityTools
description: Small-footprint Plugin for easier handling of Minecraft's Display-Entities
version: '${project.version}'
authors:
  - Velyn
main: de.nmadev.displayentitytools.DisplayEntityTools
api-version: '1.20'
website: https://github.com/Velyn-N/DisplayEntityTools
permissions:
  displayentitytools.use:
    description: "Usage Permission for DET"
  displayentitytools.admin:
    description: "Admin Permission for DET"
