name: DisplayEntityTools
description: Small-footprint Plugin for easier handling of Minecraft's Display-Entities
version: '${project.version}'
author: Velyn
main: de.nmadev.displayentitytools.DisplayEntityTools
api-version: '1.20'
website: https://github.com/Velyn-N/DisplayEntityTools
commands:
  displayentitytools:
    description: Command-Access to DisplayEntityTools
    permission: displayentitytools.use
    aliases: [det]
permissions:
  displayentitytools.use:
    description: "Usage Permission for DET"
  displayentitytools.admin:
    description: "Admin Permission for DET"
