name: Build and Release

on:
  workflow_dispatch: # for manual trigger
  push:
    tags:
      - 'v*' # for semantic versioning tags

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.release.outputs.id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Extract tag name
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update pom.xml with the tag version
        run: mvn versions:set -DnewVersion=${{ env.VERSION }}

      - name: Build with Maven
        run: mvn clean package

      - name: Clean up artifacts
        run: rm target/original-*.jar

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "DisplayEntityTools ${{ github.ref_name }}"
          draft: true
          files: target/*.jar

  finalize-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
        with:
          release_id: ${{ needs.build.outputs.release_id }}